sudo: false
language: c
virtualenv:
  system_site_packages: true
os:
  - linux
# Travis will export CC=$compiler
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libnuma-dev
    - gcc-5
    - gfortran-5
env:
    - FC=gfortran-5
before_install:
  - which $CC
  - $CC -v
  - find /usr -name gfortran\*
  - which $FC
  - $FC -v
install:
before_script:
  - ./autogen.sh
script:
  - ./configure
  - make V=1
  - make V=1 check
after_failure:
  - echo "Sad panda"
  - find . -name config.log -exec cat {} ";"
  - find . -name test-suite.log -exec cat {} ";"
notifications:
  email:
    recipients:
      - jeff.science@gmail.com
    on_success: [change]
    on_failure: [always]
